#pragma once

#define OPT_TBOOT_MS 2000
#define OPT_CPU_FREQ_HZ 72000000
#define OPT_WAIT_FOR_GETNODEINFO
#define OPT_ENABLE_WD
/* TODO: OPT_WAIT_FOR_GETNODEINFO_JUMPER_GPIO */
#define OPT_APPLICATION_IMAGE_OFFSET 8192u
#define OPT_APPLICATION_IMAGE_LENGTH 49152u

#define PORT_CAN_SILENT GPIOB
#define PIN_CAN_SILENT_INDEX 6

#define PORT_CAN_RX GPIOA
#define PIN_CAN_RX_INDEX 11

#define PORT_CAN_TX GPIOA
#define PIN_CAN_TX_INDEX 12

#define FLASH_PAGE_SIZE 2048u
